
package projeto;

import java.util.ArrayList;

/**
 *Interface onde e selecionado um bar e é exibida a guest_list do respetivo bar
 */
public class GuestList extends javax.swing.JFrame {

    ComunidadeDEI dei;
    
    /** Construtor para a criação de uma interface onde seram imprimidas as guestlists dos bares do convivio
     * @param dei objeto com as pessoas do convivio, as pessoas da comunidade e os locais do convivio
     */
    public GuestList(ComunidadeDEI dei) {
        initComponents();
        this.dei=dei;
        FillCombo();
        
    }
    
    /** Método para o preenchimento da combobox lista_locais com os bares do convivio 
     */
    public void FillCombo(){
        for(Local c: dei.getLocais_conv()){
            if(c.getLotacao()!=0)
                lista_locais.addItem(c.getNome());
        }
    }
    
    /** Método para o preenchimento da textfield onde esta a guestlist do bar selecionado na combobox em cima
     * @parm pessoas
     */
    void setLista(String pessoas){
        lista.setText(lista.getText().trim()+pessoas);
    }
    
    /** Método para o preenchimento da textfield onde esta a guestlist no caso de nao haver pessoas suficientes para fazer a guestlist
     * @parm pessoas
     */
    void setLista1(String erro){
        lista.setText(erro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        lista_locais = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lista.setColumns(20);
        lista.setRows(5);
        jScrollPane1.setViewportView(lista);

        jButton1.setText("Retroceder");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lista_locais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        lista_locais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lista_locaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lista_locais, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lista_locais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Locais(dei).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lista_locaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lista_locaisActionPerformed
        // TODO add your handling code here:
        ArrayList<Pessoa> guest_list = null;
        String aux="";
        for(Local c: dei.getLocais_conv()){
            if(((String)lista_locais.getSelectedItem()).equals(c.getNome())){
                Guest_List guest  = new Guest_List(c);
                guest_list=guest.create_guest();
            }
        }      
        if(guest_list==null){
            setLista1("Nao ha pessoas suficientes para fazer guest list");
        }
        else{
            setLista1("");
            for(Pessoa c: guest_list){
                aux=aux.concat(c.getNome()+" "+c.getPerfil()+" "+c.getCurso().trim()+"\n");
            }
            setLista(aux);
        }
        
    }//GEN-LAST:event_lista_locaisActionPerformed

  
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lista;
    private javax.swing.JComboBox<String> lista_locais;
    // End of variables declaration//GEN-END:variables
}
