/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto;

/**
 *Interface correspondente ao login onde a pessoa pode-se adicionar inscrever ou remover a sua inscriçao em locais do convivio
 */
public class Loginn extends javax.swing.JFrame {

    ComunidadeDEI dei;
    Pessoa pessoa;
    String local1;
    
    /** Construtor para a criação de uma interface onde e possivel gerir a inscriçao em locais do convivio da pessoa
     * @param dei objeto comunidadeDEI
     * @param pessoa pessoa que queremos inscrever em locais
     */
    public Loginn(ComunidadeDEI dei, Pessoa pessoa) {
        initComponents();
        this.dei=dei;
        this.pessoa=pessoa;
        FillCombo_lista_locais();
        FillCombo_seus_locais();
    }
    
    /** Método para o preenchimento da combobox lista_locais com os locais do convivio
     */
    public void FillCombo_lista_locais(){       
        for(Local c: dei.getLocais_conv()){
            lista_locais.addItem(c.getNome());
        }
    }
    
    /** Método que limpa a combobox seus_locais
     */
    public void CleanCombo(){
        for(Local c: dei.getLocais_conv()){
            seus_locais.removeItem(c.getNome());
        }
    }
    
    /** Método para o preenchimento da combobox sues_locais com os locais do convivio em que a pessoa esta inscrita
     */
    public void FillCombo_seus_locais(){
        for(Local c: pessoa.getLocais()){
            seus_locais.addItem(c.getNome());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lista_locais = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        seus_locais = new javax.swing.JComboBox<>();
        adicionar = new javax.swing.JButton();
        remover = new javax.swing.JButton();
        retroceder = new javax.swing.JButton();
        erro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lista_locais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        lista_locais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lista_locaisActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("  Locais a adicionar");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("   Seus locais");

        seus_locais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        seus_locais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seus_locaisActionPerformed(evt);
            }
        });

        adicionar.setText("Adicionar");
        adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarActionPerformed(evt);
            }
        });

        remover.setText("Remover");
        remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerActionPerformed(evt);
            }
        });

        retroceder.setText("Retroceder");
        retroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrocederActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lista_locais, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(seus_locais, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(adicionar)
                                .addComponent(remover)))
                        .addGap(17, 17, 17)))
                .addComponent(erro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 153, Short.MAX_VALUE)
                .addComponent(retroceder, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lista_locais, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(adicionar)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seus_locais, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(erro, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(remover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(retroceder, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrocederActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Pessoas pess=new Pessoas(dei);
        pess.setVisible(true);
    }//GEN-LAST:event_retrocederActionPerformed

    private void adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarActionPerformed
        // TODO add your handling code here:
        for(Local c: dei.getLocais_conv()){
            if(((String)lista_locais.getSelectedItem()).equals(c.getNome())){
                int a=pessoa.add_local(c);
                switch(a){
                    case -2:
                        erro.setText("Ja esta inscrito no local");
                        break;
                    case -3:
                        erro.setText("Nao se pode inscrever em mais de 5 locais");
                        break;
                    case 0:
                        erro.setText(((String)lista_locais.getSelectedItem())+" Adicionado com sucesso");
                        CleanCombo();
                        FillCombo_seus_locais();
                        break;
                    case -1:
                        erro.setText(((String)lista_locais.getSelectedItem())+" tem lotacao esgotada");
                        break;
                }
            }           
        }
    }//GEN-LAST:event_adicionarActionPerformed

    private void lista_locaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lista_locaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lista_locaisActionPerformed

    private void removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerActionPerformed
        // TODO add your handling code here:
        for(Local c: pessoa.getLocais()){
            if(((String)seus_locais.getSelectedItem()).equals(c.getNome())){
                pessoa.remove_local(c);
                CleanCombo();
                FillCombo_seus_locais();
                erro.setText(((String)seus_locais.getSelectedItem())+" Removido com sucesso");
                break;
            }
        }
    }//GEN-LAST:event_removerActionPerformed

    private void seus_locaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seus_locaisActionPerformed
        // TODO add your handling code here:       
    }//GEN-LAST:event_seus_locaisActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionar;
    private javax.swing.JLabel erro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> lista_locais;
    private javax.swing.JButton remover;
    private javax.swing.JButton retroceder;
    private javax.swing.JComboBox<String> seus_locais;
    // End of variables declaration//GEN-END:variables
}
