/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto;

/**
 *Interface onde se pode ver a receita total do convivio e cada receita especifica de cada bar/exposiçao
 */
public class Receita extends javax.swing.JFrame {

    ComunidadeDEI dei;
    /** Construtor para a criação de um interface onde e possivel ver a receita total dos convivios e a receita de cada bar/expoisçao
     * @param dei objeto da comunidade
     */
    public Receita(ComunidadeDEI dei) {
        initComponents();
        this.dei=dei;
        FillCombo();
    }
    /** Método para o preenchimento da label onde esta a receita de um bar/exposiçao do convivio
     * @parm receita_conv
     */
    void setLista(Float receita_conv){
        receita.setText(receita_conv.toString());
    }
    /** Método para o preenchimento da combobox lista_locais com os bares/exposiçao do convivio 
     */
    public void FillCombo(){
        for(Local c: dei.getLocais_conv()){
            if(c.getLotacao()!=0 || !c.getTipo().equals(""))
                lista_locais.addItem(c.getNome());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lista_locais = new javax.swing.JComboBox<>();
        receita = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        receita_total = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lista_locais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        lista_locais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lista_locaisActionPerformed(evt);
            }
        });

        jButton1.setText("Retroceder");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Receita Total");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(receita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lista_locais, 0, 97, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addComponent(receita_total, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lista_locais, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(receita, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(receita_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MenuPrincipal(dei).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lista_locaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lista_locaisActionPerformed
        // TODO add your handling code here:
        for(Local c: dei.getLocais_conv()){
            if(c.getNome().equals((String)lista_locais.getSelectedItem())){
                float a=c.receita();
                setLista(a);
            }
        }
    }//GEN-LAST:event_lista_locaisActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        float a=0;
        for(Local c: dei.getLocais_conv()){
            if(c.getLotacao()!=0 || c.getTipo()!=null)
                a+=c.receita();
        }
        receita_total.setText(Float.toString(a));
    }//GEN-LAST:event_jButton2ActionPerformed


   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> lista_locais;
    private javax.swing.JLabel receita;
    private javax.swing.JLabel receita_total;
    // End of variables declaration//GEN-END:variables
}
